program: /sps/t2k/eleblevec/updated_watchmal/lauch/sweep_run/run_watchmal.sh

method: random


metric:
  name: val_loss
  goal: minimize

parameters:

  # /data/dataset
  # data-dataset-parameters-config-graph_dataset_path: 
  #   value: /sps/t2k/eleblevec/datasets/graph_datasets/e_mu_500MeV_10each
  # data-dataset-parameters-config-root_file_path: 
  #   value: /sps/t2k/eleblevec/datasets/root_datasets/before_april/e_mu_500MeV_10events_each.root
  # data-dataset-parameters-config-train_keys: 
  #   value: ['time', 'charge']


  # /data/transforms
  # data-transforms-transforms-Threshold-max_thresholds:
  #   values: [[null, 400], [null, 600], [null, 1000]] 
  #   value: 7

  # /model
  model-dropout: 
    values: [0., 0.1, 0.2, 0.3]
  model-conv_in_channels:
    values : [[8, 16], [8, 16, 16], [8, 64], [8, 32, 32, 64, 64]]
  model-linear_out_features:
    values: [[8, 2], [16, 8, 2], [64, 16, 2], [64, 32, 16, 8, 2], [64, 32, 32, 2], [128, 32, 8, 2],]

  # /optimizers
  tasks-train-optimizers-lr: 
    values: [!!float 1e-3, !!float 5e-4, !!float 1e-4]
  
  # /tasks/train
  tasks-train-epochs:
    value: 150
  tasks-train-val_interval:
    value: 60
  tasks-train-data_loaders-train-batch_size: 
    values: [200, 300, 350]


command:
 - /usr/bin/bash
 - ${program}